var apiKey='d8fde320bbb942f7a45fce15dc41cdee';
List<String> countries = [
  'ae', 'ar', 'at', 'au', 'be', 'bg', 'br', 'ca','ch', 'cn', 'co', 'cu', 'cz', 'de', 'eg', 'fr',
  'gb', 'gr', 'hk', 'hu', 'id', 'ie', 'in', 'it', 'jp', 'kr', 'lt', 'lv', 'ma', 'mx', 'my',
  'ng', 'nl', 'no', 'nz', 'ph', 'pl', 'pt', 'ro', 'rs', 'ru', 'sa', 'se', 'sg', 'si', 'sk', 'th',
  'tr', 'tw', 'ua', 'us', 've', 'za',
];
List<String> countriesNames = [
  'United Arab Emirates', 'Argentina', 'Austria', 'Australia', 'Belgium', 'Bulgaria', 'Brazil',
  'Canada', 'Switzerland', 'China', 'Colombia', 'Cuba', 'Czech Republic', 'Germany', 'Egypt',
  'France', 'United Kingdom', 'Greece', 'Hong Kong', 'Hungary', 'Indonesia','Ireland','India',
  'Italy', 'Japan', 'South Korea', 'Lithuania', 'Latvia', 'Morocco','Mexico', 'Malaysia', 'Nigeria',
  'Netherlands', 'Norway', 'New Zealand', 'Philippines', 'Poland', 'Portugal', 'Romania',  'Serbia',
  'Russian Federation', 'Saudi Arabia', 'Sweden',  'Singapore', 'Slovenia', 'Slovakia', 'Thailand',
  'Turkey', 'Taiwan', 'Ukraine', 'United States of America', 'Venezuela', 'South Africa',
];


Map<String,String> countriesWithCodes = {
  'United Arab Emirates': 'ae',
  'Argentina': 'ar',
  'Austria': 'at',
  'Australia': 'au',
  'Belgium': 'be',
  'Bulgaria': 'bg',
  'Brazil': 'br',
  'Canada': 'ca',
  'Switzerland': 'ch',
  'China': 'cn',
  'Colombia': 'co',
  'Cuba': 'cu',
  'Czech Republic': 'cz',
  'Germany': 'de',
  'Egypt': 'eg',
  'France': 'fr',
  'United Kingdom': 'gb',
  'Greece': 'gr',
  'Hong Kong': 'hk',
  'Hungary': 'hu',
  'Indonesia': 'id',
  'Ireland': 'ie',
  'India': 'in',
  'Italy': 'it',
  'Japan': 'jp',
  'South Korea': 'kr',
  'Lithuania': 'lt',
  'Latvia': 'lv',
  'Morocco': 'ma',
  'Mexico': 'mx',
  'Malaysia': 'my',
  'Nigeria': 'ng',
  'Netherlands': 'nl',
  'Norway': 'no',
  'New Zealand': 'nz',
  'Philippines': 'ph',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Romania': 'ro',
  'Serbia': 'rs',
  'Russian Federation': 'ru',
  'Saudi Arabia': 'sa',
  'Sweden': 'se',
  'Singapore': 'sg',
  'Slovenia': 'si',
  'Slovakia': 'sk',
  'Thailand': 'th',
  'Turkey': 'tr',
  'Taiwan': 'tw',
  'Ukraine': 'ua',
  'United States of America': 'us',
  'Venezuela': 've',
  'South Africa': 'za',
};